# Generated by Django 5.0.6 on 2024-07-09 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(blank=True, null=True)),
                ('date', models.TextField(blank=True, null=True)),
                ('timestamp', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('url', models.CharField(blank=True, null=True)),
                ('engagement', models.IntegerField(blank=True, null=True)),
                ('public_impressions', models.IntegerField(blank=True, null=True)),
                ('estimated_views', models.IntegerField(blank=True, null=True)),
                ('liked_count', models.IntegerField(blank=True, null=True)),
                ('replied_count', models.IntegerField(blank=True, null=True)),
                ('reposted_count', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
