# Generated by Django 5.0.6 on 2024-07-09 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_sentiment_label_post_sentiment_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='medium_id',
            field=models.CharField(blank=True, null=True),
        ),
    ]
