# Generated by Django 5.0.6 on 2024-07-10 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_medium_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='id',
        ),
        migrations.AlterField(
            model_name='post',
            name='medium_id',
            field=models.CharField(primary_key=True, serialize=False),
        ),
    ]
