# Generated by Django 5.0.6 on 2024-07-10 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_remove_post_id_alter_post_medium_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='engagement',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='estimated_views',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='liked_count',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='public_impressions',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='replied_count',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='reposted_count',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='timestamp',
            field=models.CharField(blank=True, null=True),
        ),
    ]
