# Generated by Django 5.0.6 on 2024-07-10 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_alter_post_engagement_alter_post_estimated_views_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_type',
            field=models.CharField(blank=True, default='entity', null=True),
        ),
    ]
